# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: python cdk deploy

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       - uses: actions/checkout@v3

#       - name: install web app dependencies
#         working-directory: ./07-CI-CD-web/webapp
#         run: npm ci

#       - name: build web app
#         working-directory: ./07-CI-CD-web/webapp
#         run: npm run build

#       - name: install AWS CDK
#         run: sudo npm i -g aws-cdk

#       - name: install deployment dependencies
#         working-directory: ./07-CI-CD-web/py-impl
#         run: pip install -r requirements.txt

#       - name: cdk synth
#         working-directory: ./07-CI-CD-web/py-impl
#         run: cdk synth

#       - name: cdk deploy
#         working-directory: ./07-CI-CD-web/py-impl
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#         run: cdk deploy
